name: Mountie.info
favicon: null
layout_spectrum: 0.75084
typography_spectrum: 0.6430780957452953
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bf2432'
    - '#494955'
    - '#4f201a'
    - '#aba29b'
    - '#fef8e9'
  brandStrength: 0.7521735713817179
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
